### ISSUE TITLE
启动插件时出现错误

### ISSUE THREAD

**Issue by hyyy1211** [wickedll/genshin_draw_analysis#9]
阿里云部署
cnpm install 指令未发现问题
日志：
[04:03:36.837] [Android:*****] [INFO] [Event] 插件 @help 加载完成

[04:03:37.190] [Android:] [INFO] - 插件 @management 加载完成

[04:03:40.480] [Android:] [INFO] - 插件 genshin 加载完成

[04:03:40.889] [Android:] [ERROR] - 插件加载异常: Error: Cannot find module '/bot/src/plugins/genshin_draw_analysis/achieves/draw_url'
Require stack:
- /bot/src/modules/plugin.ts
- /bot/src/modules/bot.ts
- /bot/app.ts

[04:03:40.911] [Android:] [INFO] - Express 服务器已启动

[04:03:40.911] [Android:] [INFO] - 抽卡记录服务已启动

[04:03:40.931] [Android:] [ERROR] - Error: Cannot find module '/bot/src/plugins/node_modules/init'
Require stack:
- /bot/src/modules/plugin.ts
- /bot/src/modules/bot.ts
- /bot/app.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._resolveFilename (/bot/node_modules/tsconfig-paths/lib/register.js:75:40)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Function.<anonymous> (/bot/src/modules/plugin.ts:22:21)
    at step (/bot/src/modules/plugin.ts:52:23)
    at Object.next (/bot/src/modules/plugin.ts:33:53)
    at fulfilled (/bot/src/modules/plugin.ts:24:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[04:03:40.999] [Android:] [INFO] - Redis 数据库已连接

[04:03:41.299] [Android:] [INFO] - 浏览器启动成功

**Comment by hyyy1211** [comment]
后面的这个error我重装以后解决了，但是前面这个插件加载异常一直存在

**Comment by wickedll** [comment]
> 后面的这个error我重装以后解决了，但是前面这个插件加载异常一直存在

检查下文件夹名称是否正确  有没有多余的

**Comment by wickedll** [comment]
git下载的一半没有问题

**Comment by wickedll** [comment]
打包下载的应该会多个分支名称
